# Generated by Django 5.1.4 on 2024-12-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockFlowTransitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_code', models.CharField(max_length=200)),
                ('article_name', models.CharField(max_length=500)),
                ('units_before', models.FloatField(blank=True, null=True)),
                ('units_after', models.FloatField(blank=True, null=True)),
                ('registered_units', models.FloatField(default=0, null=True)),
                ('type', models.CharField(max_length=50)),
                ('batch_number_stock_in', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('unique_combined_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('sequence_number', models.PositiveIntegerField(default=0)),
                ('packed_per_type', models.CharField(blank=True, max_length=50, null=True)),
                ('order_relation_code', models.CharField(max_length=200, null=True)),
                ('order_relation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_manual_entry', models.BooleanField(default=False)),
                ('manual_entry_type', models.CharField(blank=True, choices=[('last', 'Last'), ('specific', 'Specific')], max_length=50, null=True)),
                ('manual_entry_reason', models.CharField(blank=True, choices=[('normal_sale_order', 'Normal Sale Order'), ('normal_purchase_order', 'Normal Purchase Order'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('counting', 'Counting')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockInflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_code', models.CharField(max_length=200)),
                ('article_name', models.CharField(max_length=500)),
                ('registered_quantity', models.FloatField(blank=True, default=0, null=True)),
                ('registered_gross_weight', models.FloatField(blank=True, default=0, null=True)),
                ('price_amount', models.FloatField(default=0)),
                ('amount_amount', models.FloatField(default=0)),
                ('order_code', models.CharField(blank=True, max_length=255, null=True)),
                ('order_relation_code', models.CharField(blank=True, max_length=200, null=True)),
                ('order_relation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order_delivery_date', models.DateField()),
                ('orderline_code', models.CharField(blank=True, max_length=255, null=True)),
                ('packed_per_type', models.CharField(blank=True, max_length=50, null=True)),
                ('article_quality_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_manual_entry', models.BooleanField(default=False)),
                ('unique_combined_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('sub_type', models.CharField(blank=True, max_length=100, null=True)),
                ('factor', models.FloatField(default=1.0)),
                ('batch_use_by_date', models.DateField(blank=True, default=None, null=True)),
                ('manual_entry_type', models.CharField(blank=True, choices=[('last', 'Last'), ('specific', 'Specific')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockOutflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_code', models.CharField(max_length=200)),
                ('article_name', models.CharField(max_length=500)),
                ('registered_quantity', models.FloatField(blank=True, default=0, null=True)),
                ('registered_gross_weight', models.FloatField(blank=True, default=0, null=True)),
                ('price_amount', models.FloatField(default=0)),
                ('amount_amount', models.FloatField(default=0)),
                ('order_code', models.CharField(blank=True, max_length=255, null=True)),
                ('order_delivery_date', models.DateField()),
                ('orderline_code', models.CharField(blank=True, max_length=255, null=True)),
                ('packed_per_type', models.CharField(blank=True, max_length=50, null=True)),
                ('article_quality_name', models.CharField(blank=True, max_length=255, null=True)),
                ('factor', models.FloatField(default=1.0)),
                ('type', models.CharField(default='Sales', max_length=50)),
                ('sub_type', models.CharField(blank=True, max_length=100, null=True)),
                ('unique_combined_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('order_relation_code', models.CharField(max_length=200)),
                ('order_relation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_manual_entry', models.BooleanField(default=False)),
                ('manual_entry_reason', models.CharField(blank=True, choices=[('damaged', 'Damaged'), ('lost', 'Lost'), ('counting', 'Counting'), ('normal_sale_order', 'Normal Sale Order')], default='normal_sale_order', max_length=500, null=True)),
            ],
        ),
    ]
